### ISSUE TITLE
Add license headers

### ISSUE THREAD

**Issue by dwijnand** [playframework/akka-grpc-play-quickstart-scala#11]

**Comment by raboof** [comment]
For other samples, we don't add license headers, but instead add a LICENSE file clarifying that the samples are public domain. This makes it (even) less cumbersome for users to use the samples as a basis for their own projects, since they also don't need to worry about any attribution clauses from the Apache license.

Let's do that instead?

**Comment by ignasi35** [comment]
@raboof you mean like [this one](https://github.com/akka/akka-samples/blob/2.5/akka-sample-cluster-java/LICENSE)?

**Comment by ignasi35** [comment]
related to https://github.com/lagom/akka-grpc-lagom-quickstart-scala/pull/26 and https://github.com/lagom/akka-grpc-lagom-quickstart-java/issues/9

**Comment by raboof** [comment]
@ignasi35 yes that's what I meant

**Comment by dwijnand** [comment]
Makes sense to me, and makes it less of a pain.

**Comment by ignasi35** [comment]
see https://github.com/lagom/akka-grpc-lagom-quickstart-scala/pull/28
